---
# .ansible-lint
# profile: # min, basic, moderate,safety, shared, production
#
skip_list:
  - internal-error # to prevent check vault in 'ansible-playbook --syntax-check'
  - var-naming[no-role-prefix]
  - jinja[spacing]
  - name[template]
  - no-handler
  - yaml[comments]
#
exclude_paths:
  - inventory/vault/
#
